In [ ]:
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df_raw = pd.read_csv('E0.csv')
df_raw.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [13]:
df_clean = df_raw[['Date', 'HomeTeam', 'AwayTeam', 'FTHG',
'FTAG', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 
'AC', 'HY', 'AY', 'HR', 'AR']]

df_clean.rename(columns={'FTHG': 'FullTimeHomeGoals', 'FTAG': 'FullTimeAwayGoals',
'HS': 'HomeShots', 'AS': 'AwayShots', 'HST': 'HomeShotsOnTarget',
'AST': 'AwayShotsOnTarget', 'HF': 'HomeFouls', 'AF': 'AwayFouls',
'HC': 'HomeCorners', 'AC': 'AwayCorners', 'HY': 'HomeYellowCards', 'AY': 'AwayYellowCards',
'HR': 'HomeRedCards', 'AR': 'AwayRedCards'}, inplace=True)

df_clean.dropna(inplace=True)

total_goals = df_clean['FullTimeHomeGoals'] + df_clean['FullTimeAwayGoals']
df_clean.insert(5, 'TotalGoals', total_goals, True)

df_clean.head()

,Date,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,TotalGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeFouls,AwayFouls,HomeCorners,AwayCorners,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,16/08/2024,Man United,Fulham,1,0,1,14,10,5,2,12,10,7,8,2,3,0,0
1,17/08/2024,Ipswich,Liverpool,0,2,2,7,18,2,5,9,18,2,10,3,1,0,0
2,17/08/2024,Arsenal,Wolves,2,0,2,18,9,6,3,17,14,8,2,2,2,0,0
3,17/08/2024,Everton,Brighton,0,3,3,9,10,1,5,8,8,1,5,1,1,1,0
4,17/08/2024,Newcastle,Southampton,1,0,1,3,19,1,4,15,16,3,12,2,4,1,0

In [15]:
engine = 'sqlite:///premier_league.db'
df_clean.to_sql('Matches', con=engine, index=False, if_exists='replace')

380